package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	"com.ktb.ai.core-item-catalog/graph/model"
)

// Item is the resolver for the item field.
func (r *queryResolver) Item(ctx context.Context, id int) (*model.ItemCatalog, error) {
	item, err := r.GormCatalogRepository.GetCatalogByID(id)
	if err != nil {
		return nil, err
	}

	return &model.ItemCatalog{
		ID:          item.ID,
		Price:       item.Price,
		Name:        item.Name,
		Description: item.Description,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
